### PR TITLE
Support dragging tail onto image overlay (BL-11184)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/101)

### CODE REVIEW

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/101)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @JohnThomson and @sujeffreyl)

___
*[`src/comical.ts` line 273 at r1](https://reviewable.io/reviews/bloombooks/comical-js/101#-N8Za3Er29maUvjeyo99:-N8Za3Es38kUlexfV58y:bq0vsyt) ([raw file](https://github.com/bloombooks/comical-js/blob/c318386d3f2e8afcae985d43709036fb51679079/src/comical.ts#L273)):*
> ```XML
>     }
> 
>     public static isDraggableNear(element: HTMLElement, x: number, y: number): boolean {
> ```

Seems like this is more like isDraggableOver than isDraggableNear? (since we do a hit test) Do I understand that right?

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/101)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

___
*[`src/comical.ts` line 273 at r1](https://reviewable.io/reviews/bloombooks/comical-js/101#-N8ZaFtg0TlgUH7HU1yU:-N8ZaFtg0TlgUH7HU1yV:bwfaprg) ([raw file](https://github.com/bloombooks/comical-js/blob/c318386d3f2e8afcae985d43709036fb51679079/src/comical.ts#L273)):*
> ```XML
>     }
> 
>     public static isDraggableNear(element: HTMLElement, x: number, y: number): boolean {
> ```

I think this function would benefit from some documentation about what it does/its parameters

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/101)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[`src/comical.ts` line 273 at r1](https://reviewable.io/reviews/bloombooks/comical-js/101#-N8ZaFtg0TlgUH7HU1yU:-N8_-oLU3i3tN27w4x9X:b-896fix) ([raw file](https://github.com/bloombooks/comical-js/blob/c318386d3f2e8afcae985d43709036fb51679079/src/comical.ts#L273)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I think this function would benefit from some documentation about what it does/its parameters
</blockquote></details>

Done.
___
*[`src/comical.ts` line 273 at r1](https://reviewable.io/reviews/bloombooks/comical-js/101#-N8Za3Er29maUvjeyo99:-N8_-omPDn10nvZMaIDq:bmg0du7) ([raw file](https://github.com/bloombooks/comical-js/blob/c318386d3f2e8afcae985d43709036fb51679079/src/comical.ts#L273)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Seems like this is more like isDraggableOver than isDraggableNear? (since we do a hit test) Do I understand that right?
</blockquote></details>

The new comment should explain why I prefer the current name. I haven't actually implemented the idea of being 'near' but that's how I intend it to be used.

**Review by sujeffreyl — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
