### PR TITLE
Connectors between child bubbles have constant width (BL-9082)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/73)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
I'm thinking we should bump the minor version number since this is a behavior change.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/73#-:-MJSt8UT7e1FGVG0-mZw:b-eawsk7)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/arcTail.ts, line 146 at r1](https://reviewable.io/reviews/bloombooks/comical-js/73#-MJSscGF5cxr40qrOz1u:-MJSscGF5cxr40qrOz1v:bme1c3w) ([raw file](https://github.com/bloombooks/comical-js/blob/a8a11edc550d4b9f4d946faf3bb6682326855c31/src/arcTail.ts#L146)):*
> ```XML
>         // Now we can make the actual path, initially in two pieces.
>         let bezier2: Path;
>         if (this.spec.joiner === true) {
> ```

Let's enhance the commenting a bit here , explaining why the if path is always taken but we left the else code there.
Please include the issue number.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/73)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/arcTail.ts, line 146 at r1](https://reviewable.io/reviews/bloombooks/comical-js/73#-MJSscGF5cxr40qrOz1u:-MJSxCfeDWRrFNAu9m5O:bvzn4na) ([raw file](https://github.com/bloombooks/comical-js/blob/a8a11edc550d4b9f4d946faf3bb6682326855c31/src/arcTail.ts#L146)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's enhance the commenting a bit here , explaining why the if path is always taken but we left the else code there.
Please include the issue number.
</blockquote></details>

Done.

Although, the else code is actually still very much live and the if path is definitely not always taken.
___
*[src/arcTail.ts, line 142 at r2](https://reviewable.io/reviews/bloombooks/comical-js/73#-MJSxEo1E11ZQN4nBtQl:-MJSxEo1E11ZQN4nBtQm:b8jvwi6) ([raw file](https://github.com/bloombooks/comical-js/blob/d0ce490ac403128482407a93fc8b127846039305/src/arcTail.ts#L142)):*
> ```XML
>         // prevented. So the two beziers have 'tips' just slightly different.
>         // See BL-8331, BL-8332.
>         const deltaTip = deltaMid.divide(1000);
> ```

TODO: I think I need to make a similar change for thoughtTail.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/73)* status: all files reviewed, 1 unresolved discussion

___
*[src/arcTail.ts, line 146 at r1](https://reviewable.io/reviews/bloombooks/comical-js/73#-MJSscGF5cxr40qrOz1u:-MJT1A0EBuiWcjwfWuxN:b-1qv0ff) ([raw file](https://github.com/bloombooks/comical-js/blob/a8a11edc550d4b9f4d946faf3bb6682326855c31/src/arcTail.ts#L146)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Done.

Although, the else code is actually still very much live and the if path is definitely not always taken.
</blockquote></details>

Cool. Thanks for explaining.

**Review by sujeffreyl — COMMENTED** [review]
Version number bumped from 0.1 to 0.2.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/73#-:-MJT4z8uBZgekdyfFqUs:b-gzuj37)* status: 1 of 4 files reviewed, all discussions resolved

___
*[src/arcTail.ts, line 142 at r2](https://reviewable.io/reviews/bloombooks/comical-js/73#-MJSxEo1E11ZQN4nBtQl:-MJT51H5EL1WVl2llE_7:bb6un1j) ([raw file](https://github.com/bloombooks/comical-js/blob/d0ce490ac403128482407a93fc8b127846039305/src/arcTail.ts#L142)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

TODO: I think I need to make a similar change for thoughtTail.
</blockquote></details>

Done

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/73)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
