### PR TITLE
Upgrade npm dependencies (BL-8948)

### PR DESCRIPTION
**Pull request by sujeffreyl**
---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/76)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/76)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[package.json, line 36 at r1](https://reviewable.io/reviews/bloombooks/comical-js/76#-MQTDpC_2lohI4spajVG:-MQTDpC_2lohI4spajVH:b-52ji0r) ([raw file](https://github.com/bloombooks/comical-js/blob/df2b9271aa28fe489b32e7b47c41526c610303ec/package.json#L36)):*
> ```JSON
>     },
>     "dependencies": {
>         "paper": "0.12.3"
> ```

Discussing on flowdock...

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/76)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[package-publish.json, line 3 at r2](https://reviewable.io/reviews/bloombooks/comical-js/76#-MQYKqEjCMV3WlGogjRD:-MQYKqEjCMV3WlGogjRE:b-d78yy9) ([raw file](https://github.com/bloombooks/comical-js/blob/7b49dc9f69d3f67aebe1ab50f77af3271eeb373a/package-publish.json#L3)):*
> ```JSON
> {
>     "name": "comicaljs",
>     "version": "0.3.0",
> ```

hold off, R3 is coming...

**Review by sujeffreyl — COMMENTED** [review]
I think it would be simpler to review R2 vs. R1, then R3 vs. R2, rather than R3 vs R1.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/76#-:-MQYLElUDtm3dsC2twUm:b6vii3p)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[package.json, line 36 at r1](https://reviewable.io/reviews/bloombooks/comical-js/76#-MQTDpC_2lohI4spajVG:-MQYLLidB3ndg5MPyHaf:b-896fix) ([raw file](https://github.com/bloombooks/comical-js/blob/df2b9271aa28fe489b32e7b47c41526c610303ec/package.json#L36)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Discussing on flowdock...
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 18 of 18 files at r2, 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/76)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
