### PR TITLE
BL-8537 Support partly-transparent backgrounds

### PR DESCRIPTION
**Pull request by gmartin7**
* Also added support for dragging bubbles in test code
* Original code by JT, rebased, upgraded code to use new
   paper version

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/78)

### CODE REVIEW

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/78)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @gmartin7)

___
*[src/bubble.ts, line 792 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MQwwUpR4r52AkXO7mtl:-MQwwUpR4r52AkXO7mtm:b-m196rm) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/bubble.ts#L792)):*
> ```
> relatives
> ```
This should be like "selfAndRelatives" or something like that.
___
*[src/bubble.ts, line 794 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MQwwc_kEoMhDJGT6ijM:-MQwwc_kEoMhDJGT6ijN:b-wdpiav) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/bubble.ts#L794)):*
> ```XML
>         const relatives = Comical.findRelatives(this, true);
>         if (relatives.length === 0) {
>             // just possible if this has no order
> ```

Instead of having a workaround here, I'd argue that findRelatives is implement incorrectly. In the if (!orderWithinFamily) body, it needs to check includeSelf before returning []. Then we can get rid of this workaround here in bubble.ts
___
*[src/bubble.ts, line 817 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MQwtSJMCF_PKjflcRk9:-MQwtSJNCv5hq5v3OQYK:bacpxta) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/bubble.ts#L817)):*
> ```
> ,
> ```
Unnecessary comma
___
*[src/bubble.ts, line 934 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MQwusOhCsZI6eb00roC:-MQwusOhCsZI6eb00roD:b14wkj1) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/bubble.ts#L934)):*
> ```
> alpha
> ```
I think alpha > 0 would be more human-readable
___
*[src/comical.ts, line 756 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MQwv0lIAyHzx9pl1uSd:-MQwv0lIAyHzx9pl1uSe:b-mn1s7y) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/comical.ts#L756)):*
> ```
> includeThis
> ```
I get what this means, but I think a function comment should be added for this. It could become less clear down the line.
And also add that the "this" bubble will be sorted in the appropriate place amidst its other relatives.

(Also, I would suggest includeSelf instead? but either one is fine with me)

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/78)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @gmartin7 and @sujeffreyl)

___
*[src/bubble.ts, line 794 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MQwwc_kEoMhDJGT6ijM:-MR0w6-q1aUJB_tOTq8n:b7arimt) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/bubble.ts#L794)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Instead of having a workaround here, I'd argue that findRelatives is implement incorrectly. In the if (!orderWithinFamily) body, it needs to check includeSelf before returning []. Then we can get rid of this workaround here in bubble.ts
</blockquote></details>

good idea
___
*[src/comical.ts, line 756 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MQwv0lIAyHzx9pl1uSd:-MR0wRml2z03RUaqa-Sa:bnyswpz) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/comical.ts#L756)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> includeThis
> ```
I get what this means, but I think a function comment should be added for this. It could become less clear down the line.
And also add that the "this" bubble will be sorted in the appropriate place amidst its other relatives.

(Also, I would suggest includeSelf instead? but either one is fine with me)
</blockquote></details>

I also think includeSelf is a better name. Comment could be, "Get the bubbles that are in the same canvas at the same level as the one passed, that is, the ones that are displayed linked to it. They will be sorted by their "orderWithinFamily". The bubble passed as an argument will be included in the list only if "includeSelf" is true."
___
*[src/comical.ts, line 760 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MR0xLbg7QaajYXX3ugu:-MR0xLbg7QaajYXX3ugv:b-oc14eh) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/comical.ts#L760)):*
> ```XML
>         const orderWithinFamily = bubble.getBubbleSpec().order;
>         if (!orderWithinFamily) {
>             return [];
> ```

As suggested elsewhere, if (includeSelf) {return [bubble];}

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/78)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

___
*[src/bubble.ts, line 792 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MQwwUpR4r52AkXO7mtl:-MR0ygbb3PkDy_bkQ7eC:b-896fix) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/bubble.ts#L792)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> relatives
> ```
This should be like "selfAndRelatives" or something like that.
</blockquote></details>

Done.
___
*[src/bubble.ts, line 794 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MQwwc_kEoMhDJGT6ijM:-MR111ey2OqoZlBOIK1H:b-896fix) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/bubble.ts#L794)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

good idea
</blockquote></details>

Done.
___
*[src/bubble.ts, line 817 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MQwtSJMCF_PKjflcRk9:-MR0zvKm1HE1xtUdLyFZ:b-896fix) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/bubble.ts#L817)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> ,
> ```
Unnecessary comma
</blockquote></details>

Done.
___
*[src/bubble.ts, line 934 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MQwusOhCsZI6eb00roC:-MR1-809-pwyiEX4_SjE:b-896fix) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/bubble.ts#L934)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> alpha
> ```
I think alpha > 0 would be more human-readable
</blockquote></details>

Done.
___
*[src/comical.ts, line 756 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MQwv0lIAyHzx9pl1uSd:-MR1-evb2K0aO52h8b5H:b-896fix) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/comical.ts#L756)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I also think includeSelf is a better name. Comment could be, "Get the bubbles that are in the same canvas at the same level as the one passed, that is, the ones that are displayed linked to it. They will be sorted by their "orderWithinFamily". The bubble passed as an argument will be included in the list only if "includeSelf" is true."
</blockquote></details>

Done.
___
*[src/comical.ts, line 760 at r1](https://reviewable.io/reviews/bloombooks/comical-js/78#-MR0xLbg7QaajYXX3ugu:-MR10AvE3DVcfNkK5L0I:b-896fix) ([raw file](https://github.com/bloombooks/comical-js/blob/5816487e993f650490a553ffd8575531239106e1/src/comical.ts#L760)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

As suggested elsewhere, if (includeSelf) {return [bubble];}
</blockquote></details>

Done.

**Review by sujeffreyl — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/78)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by sujeffreyl — APPROVED** [review]
:lgtm:

> Reviewed 3 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/78#-:-MR14MCe7xl2-Kd_qduS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
