### PR TITLE
BL-10002 fix delete problem

### PR DESCRIPTION
**Pull request by gmartin7**
* make remaining child inherit color from deleted parent

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/91)

### CODE REVIEW

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/91)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/comical.ts, line 794 at r1](https://reviewable.io/reviews/bloombooks/comical-js/91#-McQf-d0B3I8zdbySobe:-McQf-d2DKvc4ljDhC9d:b-93j7de) ([raw file](https://github.com/bloombooks/comical-js/blob/52032312dfaaf9b4808ac218c19e4e7488573d09/src/comical.ts#L794)):*
> ```XML
>                         relationSpec.tails[0].joiner = false;
>                     }
>                     // If there was a background color on the parent, the first child needs to "inherit" the color.
> ```

Does the same problem repro for outerOutlineColor?  cornerRadius? Shadowoffset? etc

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/91)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/comical.ts, line 794 at r1](https://reviewable.io/reviews/bloombooks/comical-js/91#-McQf-d0B3I8zdbySobe:-McQfk8B3SQqw4dh2NOb:bf0sdf2) ([raw file](https://github.com/bloombooks/comical-js/blob/52032312dfaaf9b4808ac218c19e4e7488573d09/src/comical.ts#L794)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Does the same problem repro for outerOutlineColor?  cornerRadius? Shadowoffset? etc
</blockquote></details>

At one point in the past, I wondered if perhaps everything except "order" and the "tails" are more applicable to the family than to the individual bubble.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/91)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/comical.ts, line 794 at r1](https://reviewable.io/reviews/bloombooks/comical-js/91#-McQf-d0B3I8zdbySobe:-McQh3Ek3LpotR4PpwVl:bmdm7sv) ([raw file](https://github.com/bloombooks/comical-js/blob/52032312dfaaf9b4808ac218c19e4e7488573d09/src/comical.ts#L794)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

At one point in the past, I wondered if perhaps everything except "order" and the "tails" are more applicable to the family than to the individual bubble.
</blockquote></details>

confirmed that outline color gets lost and Style!... working

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/91)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/comical.ts, line 794 at r1](https://reviewable.io/reviews/bloombooks/comical-js/91#-McQf-d0B3I8zdbySobe:-McW6UeGDHPOTr3LDXoh:b-otna4c) ([raw file](https://github.com/bloombooks/comical-js/blob/52032312dfaaf9b4808ac218c19e4e7488573d09/src/comical.ts#L794)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

confirmed that outline color gets lost and Style!... working
</blockquote></details>

Done. Much better and complete solution to the problem.

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/91)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/comical.ts, line 794 at r1](https://reviewable.io/reviews/bloombooks/comical-js/91#-McQf-d0B3I8zdbySobe:-McjxYUQ8o2xb7nlr6wI:b-pmn7ox) ([raw file](https://github.com/bloombooks/comical-js/blob/52032312dfaaf9b4808ac218c19e4e7488573d09/src/comical.ts#L794)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done. Much better and complete solution to the problem.
</blockquote></details>

1) Cool, this is pretty close to what I had in mind. I would add a comment something like this:  Most fields in the bubble spec apply to the entire family, not just to the individual bubble. The exceptions to that right now are "order" and "tails". But once relationSpec becomes the parent, its order and tail values should happen to become the same as that of the old parent.

2) I was concerned if copy by reference was OK. But I looked over the code and believe the answer is "yes, that is ok".
3) I was concerned about the order field of the other descendants. But I looked over the code and saw we already have code that updates that. So this is OK as well.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/91)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/comical.ts, line 794 at r1](https://reviewable.io/reviews/bloombooks/comical-js/91#-McQf-d0B3I8zdbySobe:-Mck-p6BCA8Le31fidDd:b-896fix) ([raw file](https://github.com/bloombooks/comical-js/blob/52032312dfaaf9b4808ac218c19e4e7488573d09/src/comical.ts#L794)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

1) Cool, this is pretty close to what I had in mind. I would add a comment something like this:  Most fields in the bubble spec apply to the entire family, not just to the individual bubble. The exceptions to that right now are "order" and "tails". But once relationSpec becomes the parent, its order and tail values should happen to become the same as that of the old parent.

2) I was concerned if copy by reference was OK. But I looked over the code and believe the answer is "yes, that is ok".
3) I was concerned about the order field of the other descendants. But I looked over the code and saw we already have code that updates that. So this is OK as well.
</blockquote></details>

Done.

**Pull request merged**
