### PR TITLE
Support simple circular bubbles (BL-9318)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/84)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
I'm a little surprised there isn't something needed to tell this it is not allowed to have a tail, but maybe that is the default?
Otherwise, this looks good to me. But how about a demo during tomorrow morning's meeting before we merge it so JH can confirm the UX?

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/84#-:-MXhYDUf3BG_xtd3UgJJ:b930hwp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
There is nothing to enforce that because I had no idea circles were not supposed to have tails, even by default, let alone that they should be forbidden.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/84#-:-MXhrBw26fCD548Hs9Iq:b-f7saqy)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by hatton — COMMENTED** [review]
Would be a good idea to read the linked discussion then, and see if what you built is what they are asking for.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/84#-:-MXhs9hQ3pWWevwthXs-:b-tqciko)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
I did look at that. Don't know why it didn't register that their example didn't have a tail. I've added a change so that circles don't have tails by default. I'm not sure that based on one example I should make them have a thick colored border by default, or add that exact color to our Outer Outline Color options. I think that could be done in Bloom, without any work in Comical, if we want it.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/84#-:-MXhu2KBDVL2wOGUgJdj:b-twjwt6)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/comical-js/84)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
